# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/berke/Desktop/OKUL/SoC/SoC_Progress/tuesday_17_05_2022.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_1/design_1_ilmb_v10_1.xci
# IP: The module: 'design_1_ilmb_v10_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/berke/Desktop/OKUL/SoC/SoC_Progress/tuesday_17_05_2022.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_1/design_1_ilmb_v10_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ilmb_v10_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/berke/Desktop/OKUL/SoC/SoC_Progress/tuesday_17_05_2022.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_1/design_1_ilmb_v10_1.xci
# IP: The module: 'design_1_ilmb_v10_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/berke/Desktop/OKUL/SoC/SoC_Progress/tuesday_17_05_2022.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_1/design_1_ilmb_v10_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ilmb_v10_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
